# Generated by Django 5.1 on 2024-09-10 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo01TipoDocumento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('un_1001', models.CharField(blank=True, db_column='UN_1001', max_length=3, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_01_TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Catalogo06DocumentoIdentidad',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('abrev', models.CharField(blank=True, db_column='ABREV', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_06_DOCUMENTO_IDENTIDAD',
            },
        ),
        migrations.CreateModel(
            name='Catalogo07TiposDeAfectacionDelIGV',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo15ElementosAdicionales',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_15_ELEMENTOS_ADICIONALES',
            },
        ),
        migrations.CreateModel(
            name='Catalogo51TipoDeOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cfcodcli', models.CharField(db_column='CFCODCLI', max_length=11, primary_key=True, serialize=False)),
                ('cfnombre', models.CharField(blank=True, db_column='CFNOMBRE', max_length=100, null=True)),
                ('direccion_receptor', models.CharField(blank=True, db_column='DIRECCION_RECEPTOR', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, db_column='CORREO', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('moneda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.CharField(db_column='id', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ESTADO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('distrito', models.CharField(max_length=32)),
                ('provincia', models.CharField(max_length=32)),
                ('departamento', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numDocUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('rznSocialUsuario', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroComprobante', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now)),
                ('codigoMoneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.codigomoneda')),
                ('tipoComprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo01tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoItem', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=11)),
                ('razonSocial', models.CharField(max_length=150)),
                ('nombreComercial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=50)),
                ('codigoPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codigopais')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalogo06documentoidentidad')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubigeo')),
            ],
        ),
        migrations.AddField(
            model_name='comprobante',
            name='adquiriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comprobantes_recibidos', to='core.entidad'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comprobantes_emitidos', to='core.entidad'),
        ),
    ]
