# Generated by Django 4.2.16 on 2024-10-29 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo01TipoDocumento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('un_1001', models.CharField(blank=True, db_column='UN_1001', max_length=3, null=True)),
                ('serieSufix', models.CharField(default='', max_length=2)),
            ],
            options={
                'db_table': 'CATALOGO_01_TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Catalogo06DocumentoIdentidad',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('abrev', models.CharField(blank=True, db_column='ABREV', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_06_DOCUMENTO_IDENTIDAD',
            },
        ),
        migrations.CreateModel(
            name='Catalogo09TipoNotaDeCredito',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo10TipoNotaDeDebito',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo15ElementosAdicionales',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_15_ELEMENTOS_ADICIONALES',
            },
        ),
        migrations.CreateModel(
            name='Catalogo51TipoDeOperacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', default='', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('tipoComprobante', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('moneda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroComprobante', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ESTADO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('distrito', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroNota', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comprobante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo10tiponotadedebito')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroNota', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comprobante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo09tiponotadecredito')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=11)),
                ('razonSocial', models.CharField(max_length=150)),
                ('nombreComercial', models.CharField(max_length=150, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=200, null=True)),
                ('codigoPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codigopais')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalogo06documentoidentidad')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubigeo')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoItem', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comprobante')),
            ],
        ),
        migrations.AddField(
            model_name='comprobante',
            name='adquiriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comprobantes_recibidos', to='core.entidad'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='codigoMoneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.codigomoneda'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comprobantes_emitidos', to='core.entidad'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadodocumento'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipoComprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo01tipodocumento'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipoOperacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo51tipodeoperacion'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipopago'),
        ),
        migrations.DeleteModel(
            name='Catalogo07TiposDeAfectacionDelIGV',
        ),
    ]
