# Generated by Django 4.2.16 on 2024-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='imagen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
