# Generated by Django 4.2.16 on 2024-10-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entidad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='catalogo01tipodocumento',
            name='serieSufix',
            field=models.CharField(default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='serie',
            field=models.CharField(max_length=4),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipoOperacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipooperacion'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipopago'),
        ),
    ]
