# Generated by Django 4.2.16 on 2024-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipooperacion_tipopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo01tipodocumento',
            name='serieSufix',
            field=models.CharField(default='', max_length=2),
        ),
    ]
