# Generated by Django 4.2.16 on 2024-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_catalogo01tipodocumento_seriesufix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='serie',
            field=models.CharField(max_length=4),
        ),
    ]
