# Generated by Django 4.2.16 on 2024-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comprobante_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeo',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ubigeo',
            name='distrito',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ubigeo',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
    ]
