# Generated by Django 4.2.16 on 2024-10-23 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ubigeo_departamento_alter_ubigeo_distrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo09TipoNotaDeCredito',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo10TipoNotaDeDebito',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroNota', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('numeroNota', models.CharField(max_length=8)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Catalogo07TiposDeAfectacionDelIGV',
        ),
        migrations.RemoveField(
            model_name='catalogo51tipodeoperacion',
            name='id',
        ),
        migrations.AddField(
            model_name='catalogo51tipodeoperacion',
            name='codigo',
            field=models.CharField(db_column='Codigo', default='', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='catalogo51tipodeoperacion',
            name='descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='catalogo51tipodeoperacion',
            name='tipoComprobante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fechaEmision',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipoOperacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo51tipodeoperacion'),
        ),
        migrations.DeleteModel(
            name='TipoOperacion',
        ),
        migrations.AddField(
            model_name='notadebito',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comprobante'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo10tiponotadedebito'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comprobante'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo09tiponotadecredito'),
        ),
    ]
