# Generated by Django 4.2.16 on 2024-10-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo51tipodeoperacion',
            name='codigo',
            field=models.CharField(db_column='Codigo', default='', max_length=4, primary_key=True, serialize=False),
        ),
    ]
