# Generated by Django 4.2.16 on 2024-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_cliente_delete_usuario_comprobante_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='estado',
        ),
        migrations.DeleteModel(
            name='EstadoDocumento',
        ),
    ]
