# Generated by Django 4.2.16 on 2024-10-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_comprobante_estado_delete_estadodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ESTADO_DOCUMENTO',
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadodocumento'),
        ),
    ]
