# Generated by Django 4.2.16 on 2024-10-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_entidad_nombrecomercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='tipoOperacion',
        ),
    ]
