# Generated by Django 4.2.16 on 2024-10-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_comprobante_tipooperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='tipoOperacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo51tipodeoperacion'),
        ),
    ]
