# Generated by Django 4.2.16 on 2024-10-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comprobante_tipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='adquiriente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comprobantes_recibidos', to='core.entidad'),
        ),
    ]
