# Generated by Django 4.2.16 on 2024-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_resumendiario_comprobante_emitidoasunat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo01tipodocumento',
            name='un_1001',
            field=models.CharField(blank=True, db_column='UN_1001', max_length=4, null=True),
        ),
    ]
